plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.notificationcapture'
version = '0.1.0'

android {
  namespace "expo.modules.notificationcapture"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.work:work-runtime-ktx:2.10.1"
  implementation "androidx.core:core-ktx:1.15.0"
  testImplementation "junit:junit:4.13.2"
}
